export { default as Logo } from './logo.png'
export { default as ChevronDown } from './chev-down.png'
export { default as ExclamationMark } from './mark.png'
export { default as Laptop } from './laptop.png'
export { default as Splash } from './splash.png'
export {default as ServiceUiUx} from './service-ui-ux.png'
export {default as ServiceDevelopment} from './service-development.png'
export {default as ServiceCloud} from './service-cloud-application.png'
export {default as ServiceAutomation} from './service-automation.png'
