export { About } from './about/about'
export { Index } from './index/index'
export { Product } from './product/product'
export { ProjectName } from './project-name/project-name'
export { Clients } from './clients/clients'
export { Services } from './services/services'
